name: Build on Pull Request

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest]
    steps:
      - name: Checkout code and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Ensure submodules are updated
        run: |
            sudo apt-get install g++ clang libelf-dev libc6-dev-i386 libdw-dev
            git submodule update --init --recursive

      - name: Run Makefile build
        run: make all

      - name: Unit test - verify dwarf output is consistent
        run: ./tests/dwarf-compare.sh
